<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.bioDS</groupId>
        <artifactId>beast-phylonco-root</artifactId>
        <version>1.3.0</version>
    </parent>

    <artifactId>phylonco-lphybeast</artifactId>
    <!-- phylonco-lphybeast version, it must be consisting with version.xml   -->
    <version>${phylonco-lphybeast.version}</version>

    <dependencies>
        <dependency>
            <groupId>io.github.linguaphylo</groupId>
            <artifactId>lphybeast</artifactId>
            <version>${lphybeast.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.github.bioDS</groupId>
            <artifactId>phylonco-beast</artifactId>
            <version>${phylonco-beast.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.bioDS</groupId>
            <artifactId>phylonco-lphy</artifactId>
            <version>${phylonco-lphy.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.4ment</groupId>
            <artifactId>flc</artifactId>
            <version>${flc.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>src/assembly/phylonco-lphybeast-assembly.xml</descriptor>
                    </descriptors>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                    <appendAssemblyId>false</appendAssemblyId>
                    <finalName>${project.artifactId}-${project.version}</finalName>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>